- doc/03_configuration.md
Now the code matches the comment.
> Fix configuration example for :kaocha.plugin.profiling/count

- doc/command_line/suite_names.md
> One word spelling fix

- doc/spec_test_check.md
- test/features/spec_test_check.feature
Fixes https://github.com/lambdaisland/kaocha/issues/116
> Correct usage documentation of :no-gen

- .circleci/config.yml
See https://circleci.com/blog/circleci-matrix-jobs/ and https://circleci.com/docs/2.0/configuration-reference/#matrix for more details.
> Switch to using CircleCI's matrix jobs feature

- doc/05_running_kaocha_repl.md
Add a note for future me to find :)
Closes #148 
Closes #147
> Add a note on live reloading at the REPL

- CHANGELOG.md
- src/kaocha/output.clj
- src/kaocha/plugin.clj
- test/unit/kaocha/plugin_test.clj
Addresses #35. 
What's left to do:
> Better plugin errors

- CHANGELOG.md
- README.md
> Fix typos in CHANGELOG and README.

- deps.edn
- test/shared/kaocha/test_helper.clj
Updates some dependencies. We probably want to be more careful about updating non-test dependencies, so I'm leaving those off for now.
> Update test deps

- CHANGELOG.md
- src/kaocha/api.clj
- test/unit/kaocha/api_test.clj
- test/unit/kaocha/report_test.clj
- test/unit/kaocha/watch_test.clj
> Provide a warning when no tests are found.

- doc/02_installing.md
- doc/04_running_kaocha_cli.md
- doc/05_running_kaocha_repl.md
- doc/06_focusing_and_skipping.md
- doc/08_plugins.md
- doc/10_hooks.md
Nothing major, just giving the docs a quick proofreading pass.
> Proofread the docs.

- .circleci/config.yml
- tests.edn
> Update tests.edn and remove now-unnecessary flag.

- src/kaocha/platform.clj
- src/kaocha/plugin/notifier.clj
- test/shared/kaocha/integration_helpers.clj
- test/unit/kaocha/plugin/notifier_test.clj
More fixes to Windows tests, including a fix to #206 .
> Fix windows tests

- .circleci/config.yml
Add the newly released Java 16.
> Add Java 16.

- CHANGELOG.md
- README.md
- src/kaocha/runner.clj
- test/unit/kaocha/runner_test.clj
Reverts lambdaisland/kaocha#246
> Revert "Feature: tools-deps exec-fn support"

- CHANGELOG.md
- src/kaocha/type/ns.clj
- test/unit/kaocha/private_test.clj
- fix the [issue 245](https://github.com/lambdaisland/kaocha/issues/245)
> fix not including private test var in building test plan - issue 245

- CHANGELOG.md
- bb.edn
- src/kaocha/runner.clj
As reported by @practicalli on Clojurians: https://clojurians.slack.com/archives/CCY2V0U6A/p1639311831022300
> Add support for watch? in exec-fn

- src/kaocha/plugin/filter.clj
If suite names are passed as arguments on the command line, than kaocha.config
already marks any other suite as `:kaocha.testable/skip`. This happens well
before any other filtering logic kicks in, so that any loading or other
processing can already safely be skipped.
This is the big difference between `bin/kaocha suite-name` and `bin/kaocha
--focus suite-name`. In the latter case we don't know if what you're telling us
to focus on is a suite, ns, or test var, so we have to load everything and then
process the filters. In the former part we know we can ignore any suite except
`suite-name` across the board.
This change makes the filter plugin also check for the skip flag on suites, in
which case it will do nothing for those suites. This saves a bit of work, and it
prevents unnecessary …
> Stop any filtering logic if a suite is already skipped

- doc/10_hooks.md
Tiny mistake in the doc, but confusing when trying it out.
Cheers
> Properly namespace a kw in the hook doc

- CHANGELOG.md
- src/kaocha/config.clj
- src/kaocha/plugin.clj
- test/unit/kaocha/config_test.clj
Fix some duplicated exit codes.
> Fix exit codes

- doc/command_line/print_config.md
- doc/plugins/notifier_plugin.md
- doc/plugins/orchestra_plugin.md
- doc/spec_test_check.md
- doc/syntax_error.md
Re-run Cucumber doc generation and check it in.
> Update features from Cucumber feature tests.

- .github/workflows/add_to_project_board.yml
Create new workflow that uses LI/open-source workflow to add new pr and new issues to project board
> LIOSS-1/automation-adding-new-pr-and-issues-to-project-board

- CHANGELOG.md
- bb.edn
- deps.edn
> Depency version bumps

- doc/01_introduction.md
Fixes #333. I think this change is pretty easy, but I could see some debate about how to describe our attitude toward breaking changes.
> Update stability statement in docs

- src/kaocha/ns.clj
- src/kaocha/plugin/alpha/spec_test_check.clj
- src/kaocha/plugin/orchestra.clj
- src/kaocha/plugin/profiling.clj
- src/kaocha/result.clj
- src/kaocha/runner.clj
- src/kaocha/specs.clj
- src/kaocha/testable.clj
- src/kaocha/type/clojure/test.clj
- src/kaocha/type/ns.clj
- src/kaocha/type/spec/test/check.clj
- src/kaocha/type/spec/test/fdef.clj
- src/kaocha/type/spec/test/ns.clj
- src/kaocha/type/var.clj
- src/kaocha/watch.clj
- test/features/plugins/orchestra_plugin.feature
- test/shared/kaocha/test_factories.clj
- test/shared/kaocha/test_helper.clj
- test/shared/kaocha/test_util.clj
- test/unit/kaocha/config_test.clj
- test/unit/kaocha/hierarchy_test.clj
- test/unit/kaocha/report_test.clj
- test/unit/kaocha/testable_test.clj
- test/unit/kaocha/type/ns_test.clj
- test/unit/kaocha/watch_test.clj
> Fixup inconsistent aliases

- CHANGELOG.md
- deps.edn
- src/kaocha/api.clj
- src/kaocha/testable.clj
- src/kaocha/type/ns.clj
> Small changes to support the new doctests type

- .circleci/config.yml
Add Java LTS release to our CI matrix.
> Add java17

- doc/10_hooks.md
> Fix documentation on what kaocha-noyoda does
