CHANGELOG.md
doc/08_extending.md
doc/plugins/hooks_plugin.md
src/kaocha/monkey_patch.clj
src/kaocha/plugin.clj
src/kaocha/plugin/hooks.clj
test/features/plugins/hooks_plugin.feature
test/unit/kaocha/monkey_patch_test.clj

This allows plugins to inspect and change test results just before they are
passed to the reporter.
Notes: 
- I had to do some wrangling to get the tests to run at all, ref the changes in monkey-patch.
- I am a little unsure of my change in `src/kaocha/plugin/hooks.clj` - I'm not sure if the hooks will be on the results.
- In the documentation I called the parameter into pre-report `results` - Is that a good name?

Add a pre-report hook

---

deps.edn
pom.xml
src/kaocha/plugin/profiling.clj

It seems to be used for only one function that is just as easily implemented
using java.time directly.
I noticed this because I got an error when trying to evaluate kaocha in the repl. It had something to do with clojure.java-time. Since it was so easy to remove, I didn't spend much time figuring out why it failed.

Remove dependency on clojure.java-time

---

src/kaocha/plugin.clj
test/unit/kaocha/plugin_test.clj

This is an initial spike at this, but there are a number of areas for improvement:
* Do you want to fail cleanly with a colourful log instead of just throwing an exception and dying? The output is pretty gross from throwing an exception, and probably not that helpful.
* Should we try and provide more descriptive error messages around `try-load-third-party-lib` as well, instead of just falling through to the :default case?
* Is the :default keyword for the multimethod ok in this context given that plugins register as keywords?
* Should this be an error case that prevents running the tests, or just prints a warning and continues? Sometimes it's better to throw an error early, rather than print a warning that can be missed and have the tests blow up in a more spectacular manner later on.
* …

Provide a more descriptive message when plugin loading fails

---

CHANGELOG.md
doc/06_focusing_and_skipping.md
src/kaocha/core_ext.clj
src/kaocha/load.clj
src/kaocha/monkey_patch.clj
src/kaocha/plugin/filter.clj
src/kaocha/report.clj
src/kaocha/type/clojure/test.clj
src/kaocha/type/ns.clj
src/kaocha/watch.clj
test/shared/kaocha/test_helper.clj
test/unit/kaocha/core_ext_test.clj
test/unit/kaocha/plugin/filter_test.clj
test/unit/kaocha/type/clojure/test_test.clj
test/unit/kaocha/type/ns_test.clj
test/unit/kaocha/type/var_test.clj

Ignore :focus-meta tags that don't match any tests. Print a warning.
@magnars I know you would prefer not to have the warnings, but I'll open a separate ticket for making the warnings configurable.
Closes #40

Run all tests when --focus-meta doesn't match

---

CHANGELOG.md
src/kaocha/api.clj
src/kaocha/config.clj
src/kaocha/core_ext.clj
src/kaocha/plugin.clj
src/kaocha/plugin/hooks.clj
src/kaocha/test.clj
test/unit/kaocha/config_test.clj
test/unit/kaocha/plugin/hooks_test.clj

This is a useful hook e.g. for setting dynamic bindings.
``` clojure
(defplugin my.ns/my-plugin
(wrap-run [run test-plan]
(fn [& args]
(binding [...]
(apply run args)))))
```

Add the wrap-run hook to the hooks plugin

---

src/kaocha/plugin/notifier.clj
test/features/plugins/notifier_plugin.feature
test/unit/kaocha/plugin/notifier_test.clj

Given the limited screen real estate notifications shouldn't be too chatty: drop
the number of assertions, and only print error/failure counts when non-zero.

Make the notifier plugin more concise

---

CHANGELOG.md
doc/plugins/bindings.md
src/kaocha/plugin/bindings.clj
test/features/plugins/bindings.feature

Configure dynamic bindings from `tests.edn`.
```
#kaocha/v1
{:plugins [:kaocha.plugin/bindings]
:kaocha/bindings {some-dynamic/*var* 123}}
```
Closes #59

Add a bindings plugin to add dynamic bindings

---

doc/08_plugins.md

I stumbled over this in the docs.

Fix docs: Plugin names should be keywords

---

src/kaocha/core_ext.clj
src/kaocha/watch.clj
test/shared/kaocha/integration_helpers.clj
test/unit/kaocha/watch_test.clj

On OSX changing files will often also emit events on the containing directory,
causing excessive test runs while in --watch mode. This manifests as duplicate
test runs, but is especially visible when ignoring certain file patterns.
This commit adds a check for directories and ignores those events.

Stop the watcher from reacting to directory events

---

src/kaocha/hierarchy.clj
src/kaocha/type/clojure/test.clj
src/kaocha/type/ns.clj
test/unit/kaocha/hierarchy_test.clj

Top level testables are called test suites, bottom level ones are called leafs,
the ones in the middle are groups. Leafs were already getting marked in the
hierarchy, now groups and suites are too.

Add hierarchy tags and helpers to mark suites and groups

---

doc/08_plugins.md

I just noticed a small mistake in the documentation, hope it helps.

Correct link to non existent file

---

doc/05_running_kaocha_repl.md
resources/kaocha/default_config.edn

Minor, unsolicited fixes
- Edit doc ch5: `test-plan` not found in `config` ns
- Remove extra closing curly in default config

Doc and default config

---

README.md
doc/03_configuration.md
doc/05_running_kaocha_repl.md
resources/kaocha/default_config.edn
src/kaocha/testable.clj

#60 "Default ns-pattern "-test$" is confusing"
#34 "Provide a warning when no tests are found"
1. Kaocha seems to be running okay out of the box without the need for a `test.edn` config file, provided some conventions are being followed. Make this the most straightforward option to get started. 
2. While the defaults make sense, a catch-all configuration example would help to get up and running quickly on existing projects, with a due statement that it is suboptimal.
3. When no tests are found, a warning should be printed, with the most obvious corrective actions briefly mentioned.

Improve quick start

---

README.md

Nasty typo in README: test.edn -> tests.edn

---

README.md
bin/check_feature
bin/check_features
bin/kaocha
bin/prep_release
bin/release
bin/run_feature
bin/update_feature
doc/02_installing.md

The path `/bin/bash` doesn't exist in  some unix systems (like [NixOS](https://nixos.org/), which I use).
In general it's more portable to use `/usr/bin/env bash` instead of `/bin/bash`, see https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability
It's just a suggestion, but I thought it would be better to offer the suggestion with a PR

Make scripts more portable, replacing  `/bin/bash` with `/usr/bin/env bash`

---

doc/04_running_kaocha_cli.md

The correct option is `--no-capture-output`, not `--no-capture`

Fix option docs for --no-capture-output

---

CHANGELOG.md
src/kaocha/classpath.clj
src/kaocha/core_ext.clj
src/kaocha/monkey_patch.clj
src/kaocha/plugin/capture_output.clj
src/kaocha/stacktrace.clj

Hey folks, thank you for the Kaocha! 
I'm running with with `*warn-on-reflection*` set as `true` and you may found useful to have these type hints as well.

Add type hints to eliminate reflection warnings

---

src/kaocha/runner.clj
src/kaocha/watch.clj

Also make sure the process exits with an exit code when this kind of exception
occurs (rather than continuing to block forever).
ping @WhittlesJr

Fix --watch without tests.edn (for real this time)

---

CHANGELOG.md
fixtures/e-tests/eee/bad_code_test.clj
fixtures/with_compile_error.edn
src/kaocha/report/progress.clj

When clojure code contained a syntax error, the progress reporter would suffer
a NullPointerException which occluded the syntax error exception.
This happened because the kaocha.report.progress :error method was being called
before the :begin-test-suite method wherein the progress bar is created.
Although I did not create automated tests to verify my fix, I did add some
fixture code to manually exercise the problem which I ran prior to and after
my fix via:
```
./bin/kaocha --config-file fixtures/with_compile_error.edn \
--reporter kaocha.report.progress/report
```
Fixes #87

Progress reporter no longer occludes syntax errors

---

CHANGELOG.md
src/kaocha/hierarchy.clj
src/kaocha/hierarchy.cljc
src/kaocha/matcher_combinators.clj
src/kaocha/report.clj
src/kaocha/type/var.clj

This is needed for the upcoming matcher-combinator support in ClojureScript.

Consolidate kaocha.hierarchy

---

README.md
doc/03_configuration.md
doc/04_running_kaocha_cli.md

kaocha.report.progress/progress only shows the bar,
kaocha.report.progress/report also shows the actual failures, so it's
probably what people want
Could also consider renaming `progress/progress` -> `progress/progress*`, `progress/report` -> `progress/progress`.

Fix documentation for progress reporter

---

README.md

Pretty sure `$@` is POSIX shell compliant, not a bash-ism.

removing requirement on bash

---

doc/03_configuration.md
src/kaocha/config.clj

Fixes #127 
I suspect the diff coverage fell beneath the threshold because I also moved a function down within the file.
There are no tests for this feature.  I can add some but not sure how best to test it without testing meta-merge.  Could maybe just test a file the meta-merge tag in it doesn't fail a call to read?

Introduce a meta-merge aero tag

---

CHANGELOG.md
src/kaocha/plugin/filter.clj
test/unit/kaocha/plugin/filter_test.clj

Instead of processing all focus/meta directives at once, first process the test
plan to skip tests based on test-suite level config in tests.edn, then do a
second pass based on CLI args, so that CLI args can only narrow down the
original selection.
Co-authored-by: Slawomir Gonez
Closes #126

Apply focus/skip/-meta in two stages, first test suite, then CLI

---

src/kaocha/watch.clj
test/unit/kaocha/watch_test.clj

Closes #133 
Rebinding the current set of dynamic variables in the `future` allows dynamic variables to be rebound in tests.

Fix #133: cannot set dynamic variables in --watch mode

---

src/kaocha/report.clj

This commit allows for the `expect` macro in Clojure Expecations to be
supported in Kaocha, starting with the equality operation.
Fixes #136
-=david=-

Support Clojure Expecations For Colourised Output

---

CHANGELOG.md
bin/prep_release
deps.edn
src/kaocha/load.clj
src/kaocha/report.clj
src/kaocha/testable.clj

When a test namespace has an ns form that can't be read by tools.namespace, then
tools.namespace would simply pretend that ns did not exist, and we would happily
carry on from there. This is problematic, people should be notified when we are
unable to load a test file.
We've updated our fork of tools.namespace to return these errors including the
file name context, which we then use to turn them into load errors.
When a load error is encountered the test is not run, but it's reported as an
error through the configured reporter. Any sibling tests are skipped.
Closes #135

Report bad ns form

---

CHANGELOG.md
src/kaocha/plugin/orchestra.clj
src/kaocha/plugin/preloads.clj
test/features/plugins/orchestra_plugin.feature

This is a pair of plugins that let you require namespaces (e.g. spec namespaces), and run Orchestra's instrument and instrument at the right points in the test lifecycle.
I've had a go at running the tests but I wasn't able to get them going on macOS.
Feedback welcome!

Add orchestra and require-ns plugins

---

CHANGELOG.md
src/kaocha/plugin/hooks.clj
test/features/plugins/hooks_plugin.feature

This will be how in kaocha-cljs2 people decide how to compile their ClojureScript and launch their JS runtime.

[hooks plugin] Implement before/after hooks on the test suite level

---

.circleci/config.yml
doc/spec_test_check.md
src/kaocha/plugin/alpha/spec_test_check.clj
src/kaocha/result.clj
src/kaocha/testable.clj
test/unit/kaocha/plugin/alpha/spec_test_check_test.clj
tests.edn

* Prefer CLI options over config values
* Enable test.check plugin in tests.edn
* Disable some generative fdef checks for functions without adequate generators
Resolves #156.

Fall back to config values in test.check plugin

---

README.md
doc/03_configuration.md

Addressing #167, I took some information from the README and copied it to the Configuration section.
Obviously, we don't want too much duplication in the docs, but I think this is important enough for newcomers to Kaocha to have in both places.

Copy useful information about defaults from README to the Configuration

---

.circleci/config.yml
CHANGELOG.md
src/kaocha/plugin/alpha/spec_test_check.clj
src/kaocha/specs.clj
src/kaocha/type/clojure/test.clj
src/kaocha/type/spec/test/check.clj
src/kaocha/type/spec/test/fdef.clj
src/kaocha/type/spec/test/ns.clj
test/unit/kaocha/plugin/alpha/spec_test_check_test.clj
tests.edn

- The STC plugin now respects config precedence. CLI options always override test suite and global configuration. Test suite configuration takes precedence over global configuration.
- The STC plugin now reads the suite IDs from config to determine if it needs to skip any config overriding when test selectors are provided, rather than just checking against the static :generative-fdef-checks selector.
- The STC runner now adds test suite configuration to the generated fdef testables. Previously, no options specified within the test suite were respected by the fdef runner.
Resolves #160.

STC plugin and runner improvements

---

doc/02_installing.md

Since a test runner is a core part of the dev workflow, it makes more sense to add Kaocha as a dependency to `:dev` than as as separate profile. 
It does sometimes make sense to use a separate profile, so I'm keeping that information but putting it in a separate section that clarifies the tradeoffs.
Addresses #118 and #166.

Update docs to suggest using :dev profile for Leiningen

---

CHANGELOG.md
src/kaocha/specs.clj

Use wrappers for `s/gen` and `s/with-gen`, when we are unable to load
test.check.generators we use simple stubs.
Fixes #159

Make sure we can still run Kaocha when test.check is not available

---

doc/05_running_kaocha_repl.md

Problem: Docs for using koacho with REPL is using `use`
Solution: avoid `use` and be more explicit with `require`
Optionally example could have used `(requrie '[kaocha.repl :as k :refer [run]])` but `run` is a common name which may exist in users namespace.

docs: change `use` to `require` in REPL example

---

.circleci/config.yml
src/kaocha/runner.clj

Addresses #36 using @plexus's suggested solution of adding a spec validation check early on.
I added a simple exception handler to just print the exception name and spec failed message, so it looks like the following:
```
java.lang.AssertionError: -- Spec failed --------------------
{:kaocha/bindings ...,
:kaocha/tests ...,
:kaocha/fail-fast? ...,
:kaocha/color? ...,
:clojure.spec.test.check/instrument? ...,
:kaocha/plugins
[... ... ... kaocha.plugin.alpha/info ... ... ... ... ...],
^^^^^^^^^^^^^^^^^^^^^^^^
:kaocha/reporter ...,
:clojure.spec.test.check/check-asserts? ...,
:kaocha.hooks/pre-load ...}
should satisfy
keyword?
-- Relevant specs -------
:kaocha/plugins:
(clojure.spec.alpha/coll-of clojure.core/keyword?)
:kaocha/config:
(clojure.spec.alpha/keys :req ~(conj global-opts …
```

Add spec validation for the list of plugins.

---

src/kaocha/specs.clj

Users are still running into issue #159. It happens soon after starting `bin/kaocha` because the problematic spec is used to check the config.
I narrowed it down, and the problem is in the`kaocha/report` spec. `clojure.spec.alpha.fspec` actually requires test.check, which is [a known limitation](https://clojure.atlassian.net/browse/CLJ-1936#icft=CLJ-1936). ~~To fix this, I used the same technique as in #171 .~~ (see comment below)

Ensure runner works without test.check.

---

src/kaocha/specs.clj

`kaacha` -> `kaocha`
Nothing more :)

Fix spelling in spec name

---

src/kaocha/specs.clj

The arguments to ex-info in this generator were transposed. Previously, any time spec tried to generate a `:kaocha.test-plan/load-error`, it threw a ClassCastException.

Fix arg order in load-error generator

---

CHANGELOG.md
src/kaocha/api.clj
src/kaocha/core_ext.clj
src/kaocha/plugin.clj
src/kaocha/repl.clj
src/kaocha/runner.clj
src/kaocha/version_check.clj
test/unit/kaocha/version_check_test.clj

Addresses #37. Checking for the Clojure version is a bit tricky because the initial errors come during the import process, so they can't be handled during the normal program flow. 
The only alternative I came up with would be to enclose problematic imports in `try`s. Since we don't support earlier versions, littering the codebase with checks for it seems like a bad tradeoff.

Throw error when on a version of Clojure prior to 1.9.

---

CHANGELOG.md
README.md
src/kaocha/config.clj
src/kaocha/runner.clj

If we change the defaults and create a new reader literal for them, `#kaocha/v2`, people with a tests.edn will be fine—they're either using a completely custom config or they're loading a set of defaults they're happy with using `#kaocha/v1`. However, people not using a configuration file at all might see changes in behavior.
To help avoid this, we should warn users when they don't have a configuration file.
```
WARNING: Did not load a configuration file and using the defaults.
This is fine for experimenting, but for long-term use, we recommend creating a configuration file to avoid changes in behavior between releases.
To create a configuration file using the current defaults, create a file named tests.edn that contains 'kaocha/v1 {}'.
```

Warn when the user has no config

---

.circleci/config.yml

While the Clojure team generally recommends LTS releases, between 10 and 30 percent of Clojure users target more recent versions. Plus, if there's an incompatibility introduced after Java 11, it would be good to know now, rather than when we add the next Java LTS.

Add Java 15 to our test matrix.

---

README.md

Fix the tests.edn in the README. Small change, but lets someone copy and paste it directly if they want.

Balance braces in example tests.edn in README

---

CHANGELOG.md
src/kaocha/plugin/notifier.clj

On Windows, there's no `which` command, so our attempt to determine if commands exist fails with an unhelpful error. Addresses #198.

Extend exists? to not cause an issue on Windows.

---

src/kaocha/plugin/notifier.clj

The JVM has built-in functionality for notification messages. We don't want to replace the existing use of `notify-send` and `terminal-notifier` because the JVM notifications don't look great on every platform, but it works as a fallback.

Add support for Java's notification messages.

---

doc/03_configuration.md

Document the skip-add-classpath? flag

---

bin/kaocha

Arne suggested this, and it's much easier than rewriting the tests to not use `\n`. Addresses #206.
Tests

Set the line endings in the JVM to be consistent across platforms.

---

deps.edn

Running `bin/kaocha` previously warned you about unqualified libs in `deps.edn`: 
```
DEPRECATED: Libs must be qualified, change aero => aero/aero (deps.edn)
DEPRECATED: Libs must be qualified, change orchestra => orchestra/orchestra (deps.edn)
DEPRECATED: Libs must be qualified, change slingshot => slingshot/slingshot (deps.edn)
DEPRECATED: Libs must be qualified, change meta-merge => meta-merge/meta-merge (deps.edn)
DEPRECATED: Libs must be qualified, change hawk => hawk/hawk (deps.edn)
DEPRECATED: Libs must be qualified, change progrock => progrock/progrock (deps.edn)
DEPRECATED: Libs must be qualified, change expound => expound/expound (deps.edn)
```
(This wouldn't happen to users of the library.)
This PR cleans that up.

Update deps.edn to have namespaces in order to silence warning.

---

bb_deps.edn
src/kaocha/api.clj
test/unit/kaocha/version_check_test.clj

When files fail to parse then it's likely no tests can be loaded, in that case
we need to show the error, not the generic "check your config" message.
This should go a long way towards addressing #208, although there still may be other cases where the load error doesn't properly come through.

Don't let the "no tests found" message shadow the load error

---

CHANGELOG.md
src/kaocha/plugin/print_invocations.clj

If you run `./bin/kaocha --no-capture-output` and a test fails, it suggests using `bin/kaocha --capture-output false --focus '...'`, which if you try to run it fails with `No such suite: :false, valid options: :unit.` since the `--capture-output` option does not expect any parameters.
To fix this, I added handling for boolean options so that they should get printed correctly.

Fix print-invocations for boolean flags

---

src/kaocha/api.clj
src/kaocha/plugin.clj
src/kaocha/repl.clj
src/kaocha/runner.clj

Attempted fix of #239. It appears that, in some cases, a Clojure file can be loaded before clojure.core is required,
so calling require before ns causes issues.

Add namespace to usages of require.

---

README.md

Addresses #241. This moves down the section on supporting Kaocha via Open Collective to match our convention in other repositories and adds a link to jump to the Quick start.

Move up quick start

---

.circleci/config.yml
CHANGELOG.md
bin/kaocha
deps.edn
dev/user.clj
src/kaocha/api.clj
src/kaocha/plugin/notifier.clj
src/kaocha/plugin/profiling.clj
src/kaocha/report.clj
src/kaocha/runner.clj
src/kaocha/specs.clj
src/kaocha/testable.clj
src/kaocha/type/ns.clj
src/kaocha/type/spec/test/ns.clj
src/kaocha/util.clj
src/kaocha/watch.clj
test/features/plugins/orchestra_plugin.feature
test/shared/kaocha/integration_helpers.clj
test/shared/kaocha/test_helper.clj
tests.edn

This makes kaocha.watch use the mechanisms already available in
`kaocha.testable` to deal with and report load errors. It also does a general
pass of cleaning things up, because we had created a bit of a mess.
`handle-load-error` is gone, the testable implementations should no longer need
this, just let kaocha.testable handle this stuff for you.
It also seems at some point we went from `:kaocha.test-plan/load-error` to
`:kaocha.testable/load-error`, and ended up with a bit of a hodge-podge. It's
surprising things still worked as well as they did. I changed the remaining
test-plan/load-error references to testable/load-error, since that now
dominates, and is IMO also the more intuitive, since we apply these on
individual testables (typically the suite).
I removed the Orchestra …

Fix and clean up load-error handling, remove Orchestra

---

CHANGELOG.md
README.md
src/kaocha/runner.clj
test/unit/kaocha/runner_test.clj

I added a new `kaocha.runner/exec` entrypoint to allow usage from tools-dep's new -X feature. All it does is convert the `:exec-args` map to a list of CLI args and passes that to the existing `-main`.
This has the nice side effect of allowing you to load the `:test` alias in a REPL without either a) running all of your tests on load if you have a `:main-opts` directly in your alias map or b) requiring that you have a separate wrapper script that specifies the main ns to invoke to avoid a. But of course you can still have a wrapper script if you like. :)
Quick and dirty (too quick and dirty?) :)

Feature: tools-deps exec-fn support

---

CHANGELOG.md
README.md
doc/02_installing.md
src/kaocha/runner.clj

Adds an entry point for using Kaocha with the `exec-fn`/`-X` feature of Clojure CLI tools.
While my name's on the commit, @plexus wrote the code and @cap10morgan wrote the basis of the documentation and tests. Thanks!

Add exec fn

---

test/unit/kaocha/api_test.clj
test/unit/kaocha/type/clojure/test_test.clj
test/unit/kaocha/type/ns_test.clj
test/unit/kaocha/type/var_test.clj

Fixes #252.
Clojure 1.11 add the function run-test, which conflicted with a test in several namespaces.
This changes the :refer :all to be specific to the symbols we actually need.

Fix several tests for Clojure 1.11

---

.circleci/config.yml
test/unit/kaocha/plugin/notifier_test.clj
test/unit/kaocha/watch_test.clj

This adds Windows to our CI configuration. Once this is figured out, it can serve as a template for other projects. We still have some outstanding issues with these tests, so I'll either wait to merge this or skip the problematic tests on just our Windows build.

Add Windows CI

---

src/kaocha/api.clj
src/kaocha/plugin/filter.clj

Currently this leads to an unfortunate interaction where if you `--focus
foo/bar`, but `foo.clj` fails to load, then there is no `#'foo/bar`, and the `foo`
ns gets skipped, even though the `foo` ns actually has a load error which we
need to show the user.
So: never mark testables with load errors as to be skipped, we're better off
being cautious here and always surfacing load-errors.
I just ran into this by getting the dreaded "no tests found" message when using a `--focus` flag. Without the `--focus` I got to see the actual error. This should fix that.

Don't skip tests with load errors

---

src/kaocha/repl.clj

Addresses #231 by adding a basic message instead of letting errors bubble up.
I found calling `kaocha.repl/run` with a fake test-id was an easy way to trigger an early-exit error.

Catch early-exit errors in Kaocha.repl

---

CHANGELOG.md
deps.edn
doc/07_watch_mode.md
src/kaocha/watch.clj

hawk is using an old version of JNA which breaks file watching on m1 macs.
The alternative was to use :polling or :java but they were either too slow
or consumed lots of battery
[beholder](https://github.com/nextjournal/beholder) seems to be maintained, fast, and a much cleaner approach.
figwheel has also shifted to using beholder instead of hawk. shadow-cljs
also got rid of hawk
maybe beholder should just replace hawk altogether?
cc: #151 , https://github.com/thheller/shadow-cljs/commit/f3b89b5a3d0f35b78f0be9e457f78a70c0d7bf04 , https://github.com/bhauman/figwheel-main/pull/299

Add nextjournal/beholder as an alternative watcher

---

CHANGELOG.md
src/kaocha/config.clj
src/kaocha/runner.clj

This is useful for occasionally overriding the tests.edn setting.

Add --no-fail-fast CLI option

---

test/unit/kaocha/watch_test.clj

From the original PR (#64), fixes #190:
>I discovered that the watch-test had an (is a b) type bug - it wasn't verifying its assertion. Kaocha can catch those, can't it? :)
>Anyway, I added in the equals, and further discovered that the test wasn't producing the expected outcome. On my system (OSX) I needed to manually trigger an event to see the second run in the output. The test is still failing though, as I'm not seeing the "Reloading #{foo.bar-test}" part in my test run. I figured maybe you'd catch this more easily than me?
I haven't made any changes besides rebasing it, but I'm not making changes to the original PR for posterity. The key change seems to be Mitesh's addition of the beholder watcher (#268).

Partially fix watch test bug

---

CHANGELOG.md
src/kaocha/plugin/gc_profiling.clj

Fixes #281. Apparently, syntax errors prevent tests from running, so there's no results to calculate the length of in `post-summary`. I wasn't able to reproduce the original bug directly, but I was able to reproduce the issue with the anonymous function.

Fix profiling plugin.

---

CHANGELOG.md
src/kaocha/watch.clj

Fixes #277 by looking for both `:create` and `:modify` events raised by beholder.
We could also look for `:delete` events. That wouldn't be necessary for the bug, but it might make more sense conceptually.

Reload on :create events.

---

CHANGELOG.md
src/kaocha/config.clj
test/unit/kaocha/config/included-test.edn
test/unit/kaocha/config/loaded-test-resource.edn
test/unit/kaocha/config/loaded-test.edn
test/unit/kaocha/config_test.clj

This could be convenient when kaocha needs to be invoked from code where the contents of the classpath are more reliable than dealing with file system paths.

Extend load-config to also work on resources

---

README.md

Fix punctuation issues and actualize copyright year in README

Fix punctuation issues and actualize copyright year

---

test/unit/kaocha/watch_test.clj
tests.edn

There's a watch test that sometimes fails on our Java 1.8 runners (although it works on my Ubuntu machine). These tests are useful, but difficult to get right, and so I don't think troubleshooting it is worth it. 
At some point, we'll want to drop Java 8, but it's here to stay for a long time yet so I think disabling this one particular test makes the most sense.

Disable sporadically failing test on Java 1.8.

---

src/kaocha/api.clj
src/kaocha/testable.clj

Previously, when filtering on a non-existent test, we'd get our existing warning about no tests being found. Unfortunately, this warning only mentions `ns-patterns` or `test-paths` (#289).
This PR fixes this by adding a new warning message for the filtering and softens the wording on the existing message.

Fix "no tests" message

---

.circleci/config.yml

I had some issues with #296, as upgrading the Clojure orb mysteriously makes one of our tests non-deterministic. However, just adding Clojure 1.11 doesn't require changing the orb, so hopefully this will work and we can come back and figure out the issue with #296 later.

Add Clojure 1.11

---

.circleci/config.yml

We're a bit behind on testing Kaocha against the latest versions of Java and Clojure. Probably no huge issues or we would have heard by now, but still worth testing, IMO.

Add latest versions of JDK and Clojure

---

CHANGELOG.md
src/kaocha/plugin/profiling.clj

Plugin authors (like myself) might want to consume profiling data as
part of their plugin. Having these specs available is useful for those
authors so they can write their own specs against this data without
having to violate boundaries and define the specs themselves.

Add specs for profiling plugin data

---

CHANGELOG.md
deps.edn
pom.xml
src/kaocha/assertions.clj
src/kaocha/matcher_combinators.clj
src/kaocha/output.clj
src/kaocha/report.clj
test/unit/kaocha/output_test.clj
test/unit/kaocha/report_test.clj

Upgrade from deep-diff1 to deep-diff2 since deep-diff1 is no longer
actively maintained. Resolves #306, #307.

switch to deep-diff2

---

doc/plugins/notifier_plugin.md
src/kaocha/plugin/notifier.clj

Add some helpful context when the system isn't able to display a notification message. From my observations on CircleCI, it appears the HeadlessException doesn't actually fire. Not sure why!
I realized after making and committing this change that an alternative/additional approach would be to disable notifier when the CI environment variable is set. I wasn't able to think of any situations where CI would be set and the user would want to see a notification, but it probably merits more thought. I want to be very careful before applying this kind of "smart" configuration because if it fails, it can be confusing and more frustrating than an extraneous warning.

Improve warning when notification can't appear.

---

doc/03_configuration.md
src/kaocha/config.clj
test/unit/kaocha/config_test.clj

Adds some documentation about meta-merge, including some examples. I'm not 100 percent sure about what is automatically meta-merged, hence the draft.
Addresses  #184.
Questions:

Initial draft of material about meta-merge.

---

CHANGELOG.md
src/kaocha/watch.clj

When using profiles with --watch, the initial configuration would be loaded with the desired profile, but subsequent ones would use the :default profile. This is because it would use the initially parsed configuration to run the tests, but then, upon rerunning the test, reload the configuration without taking into account the profile.
Fixes #310

Ensure --watch respects the profile on reload.

---

CHANGELOG.md
doc/plugins/notifier_plugin.md
src/kaocha/config.clj
src/kaocha/plugin/notifier.clj
src/kaocha/repl.clj
test/unit/kaocha/plugin/notifier_test.clj

The timeout doesn't work in all situations, including with terminal-notifier on macOS, with Java's built-in TrayIcon, or with notify-send on certain platforms. 
Partially fixes #311 and fixes #102.

Add timeout to notify-send command, plus commandline option.

---

.circleci/config.yml
test/features/command_line/print_config.feature
test/step_definitions/kaocha_integration.clj

Adds the latest LTS (17) and the latest interim release (19).

Add Java 17 and 19 to test matrix

---

test/features/command_line/print_config.feature

Quick addition to document that we aren't making guarantees about the order of keys in `--print-config`.

Document nondetermism in --print-config.

---

CHANGELOG.md
src/kaocha/type/spec/test/check.clj

`condp` using `cond`-like `:else`, resulting in a "no case found" error when `:kaocha.spec.test.check/syms` is a collection.

fix unreachable case when :kaocha.spec.test.check/syms is a collection

---

doc/08_plugins.md
src/kaocha/plugin/preloads.clj

Two small changes:
* Tweak namespace docstring for kaocha.plugin.preloads. 
* Added note about the ClojureScript limitation to the plugins article.

Update preload docs

---

doc/10_hooks.md

This documentation is misleading; `wrap-run` hooks do not receive two arguments but a single one, being `run`. We can see this here
https://github.com/lambdaisland/kaocha/blob/c3b4bfb78287988c1bdba8827c0e4369252ca8fd/src/kaocha/plugin/hooks.clj#L90-L91
Writing a wrap-run hook that takes two arguments will throw an `ArityException` when running tests.

Correct documentation of `wrap-run` hooks

---

test/features/command_line/capability_check.feature

The title and first sentence of this doc page are incorrectly combined: https://cljdoc.org/d/lambdaisland/kaocha/1.71.1119/doc/capability-check-for-org-clojure-tools-cli-if-a-project-s-dependency

Fix `Capability check for org.clojure/tools.cli` doc formatting

---

CHANGELOG.md
src/kaocha/watch.clj

Not only does  watching individual files not work with Beholder, when using Beholder on Windows, it actually crashes. This PR disables watching `tests.edn` when using Beholder as as temporary fix, as proposed by @colin-p-hill in #270 .

Fix Windows crash when using `--watch`

---

CHANGELOG.md
src/kaocha/api.clj
src/kaocha/config.clj
src/kaocha/repl.clj
src/kaocha/runner.clj
src/kaocha/watch.clj
test/features/config/warnings.feature
test/unit/kaocha/config/loaded-test-profile.edn
test/unit/kaocha/config/loaded-test-spec-mismatch.edn
test/unit/kaocha/config_test.clj
test/unit/kaocha/repl_test.clj
test/unit/kaocha/watch_test.clj

There's duplicated config logic across `kaocha.runner` and `kaocha.watch`.
In addition to simplifying maintenance, this change would:
* Avoid future issues where configuration loading diverges in `kaocha.runner` and `kaocha.watch`, like #310.
* Provide an easy way to work with configuration at the REPL.
* Allow watch to display errors when an invalid configuration is reloaded.
Relatedly, we may be able to address this TODO:
```
;; TODO: we're calling the config hook here in multiple places, and it's also
;; being called in `kaocha.api`. Given that we already need the fully expanded
;; config here (since now we're potentially adding suites in the config hook),
;; we should call it once at the top here, and pass the processed config into
;; kaocha.api. Punting on that because it requires a …
```

Refactor configuration loading to reduce duplicated code

---

CHANGELOG.md
src/kaocha/watch.clj

Close #372 
This keeps watch mode active even in the presence of circular dependencies. Basically, a tool.namespace cyclic deps error is now treated as a normal compilation error from the user's perspective.
I tested this successfully against the minimal reproduction: https://github.com/frenchy64/kaocha-circular-watch-reprod/pull/1
I tried this this on a larger project and first impressions are positive. I let the tests run through once, then intentionally added a circular dep to one of the core namespaces (depended on by dozens of files), then removed it. It behaved as expected and the process was not killed.
<details>
<summary>Full transcript</summary>
```
$ ./script/watch-checker
+ ./bin/kaocha :checker --watch
Checking out: https://github.com/frenchy64/kaocha.git at …
```

Gracefully handle circular dependencies in watch mode

---

CHANGELOG.md
src/kaocha/type/var.clj
test/unit/kaocha/post_assertion_test.clj

Moving the `type/report-count` portion of `testable/-run :var` into `test-var` wrapped it in the `join-fixtures` calls, meaning that the `is` assertion was in the tail position and returned the result (a boolean) instead of returning the merged `testable` object.
To fix, I've pulled the `type/report-count` portion back into `testable/-run :var` and have added a top-level test that fail without this change.
Closes [#384](https://github.com/lambdaisland/kaocha/issues/384)

Fix :each fixture wrapping

---

deps.edn
src/kaocha/classpath.bb
src/kaocha/core_ext.clj
src/kaocha/platform.clj
src/kaocha/plugin/notifier.clj
src/kaocha/systray.bb
src/kaocha/systray.clj
src/kaocha/util.clj

Generally try to move towards code that simply works on both platforms, when that's not possible factor out platform-specific code in platform-specific files (.bb vs .clj).
This way `if-babashka` isn't needed.
Note that normally we have a `.platform` namespace with all the platform specific bits, e.g. https://github.com/lambdaisland/uri/tree/main/src/lambdaisland/uri , but `kaocha.platform` was already taken, and I ended up introducing separate `kaocha.classpath` and `kaocha.systray` split namespaces. Maybe `kaocha.platform.systray` and `kaocha.platform.classpath` would be better.
`watch-load-error-test` seems to hang right now, probably due to the exception handling refactoring. I like how it simplifies things, but it does introduce a bit of change. I think relying on specific ex-data …

More babashka compat

---

src/kaocha/ns.clj

Ensure libs are loaded (and don't just have an alias) before skipping them in our loading code in kaocha.ns. Fixes #390.

Load namespaces first required with :as-alias

---

src/kaocha/plugin/capture_output.cljc

Quick fix to address a Cljdoc issue caused by the analysis trying to interpret one of our namespaces, moved to a `.cljc` with ClojureScript.

Fix cljdocs again

---

doc/cljdoc.edn
src/kaocha/plugin/capture_output.cljc

I realized my quick fix won't work because the other namespaces aren't available in ClojureScript either. So this change will prevent Cljdocs from trying to analyze Kaocha as a ClojureScript project.

Fix Cljdocs (again)

---

CHANGELOG.md
deps.edn

Beholder released a fix for certain editors that create a new file and then delete instead of modify. I believe Vim and Neovim do this when `noswapfile` and either `backupcopy=no` or `backupcopy=auto` are set, but other editors probably do it too.
Sometimes these creation events would be dropped because the file exists already. I haven't noticed this problem when using --watch with Neovim, but it may depend on timing and thus may be highly platform-, version- or setup-specific. Also, I consider this a safe change to make without reproducing the initial issue.

Update Beholder to improve support for certain editors.

---

CHANGELOG.md
README.md
src/kaocha/runner.clj

This adds support for the following exec-args when using the Clojure CLI exec-fn / -X invocation method:
- `:print-config true`
- `:print-test-plan true`
Fixes #401

Feature: exec-args support for print-config & print-test-plan

---

CHANGELOG.md
deps.edn
src/kaocha/watch.clj
test/unit/kaocha/watch_test.clj

Wrap the callsite to api/run in the watcher with the post-summary hook, exactly as in the runner.

332 plugin kaocha plugin profiling does not run when watch is used

---

.gitignore
CHANGELOG.md
src/kaocha/plugin/print_invocations.clj

When invoking with no extra arguments the output of `:print-invocations` would have a stray (double) space. e.g.
```
bin/kaocha  --focus 'kaocha.type.ns-test/run-test-parallel'
-----------^
```
Get rid of that.

Clean up output of :print-invocations

---

.github/workflows/canary.yml
test/bb/kaocha/canary.clj

Run tests in various repositories using the latest Kaocha. 
Addresses #291 and #301.

Add "canary" tests.

---

src/kaocha/api.clj

From #416, there is a bug raised. The bug is because that Clojure's `*out*` is not totally equivalent to java's `System/out`. Clojure's `*out*` is equivalent to System/out, wrapped in an OutputStreamWriter. Therefore, it caused a Casting error. 
After referencing how output capture is implemented in `src/kaocha/plugin/capture_output.cljc`, although I think there is already a `finally` section, which should restore the java's `System/out` and `System/err`, I tend to believe that Arne's comment is based on his real world experiments. 
```
;; Force reset printing to stdout, since we
;; don't know where in the process we've
;; been interrupted, output capturing may
;; still be in effect.
```

fix the issue from kaocha #416: casting *out* to System/out

---

CHANGELOG.md
src/kaocha/watch.clj

This fixes a problem where watching silently fails to happen when paths don't exist.
Tests (with `bin/kaocha`) are still passing.

Fix watching when paths don't exist

---

CHANGELOG.md
src/kaocha/watch.clj

DRAFT: Awaiting `lambdaisland.tools.namespace.repl/remove-disabled` to be made public — the subject of another PR (https://github.com/lambdaisland/tools.namespace/pull/5).

Respect disabling of unload/reload when watching

---

CHANGELOG.md
doc/config/bindings.md
src/kaocha/stacktrace.clj
test/features/config/bindings.feature
tests.edn

Resolves #58 
This is directly based on @pesterhazy's PR https://github.com/lambdaisland/kaocha/pull/321
What I've added:
- made the binding dynamic, making it possible to rebind in your tests.edn
- added a line to the docs
- added tests for both existing stacktrace filtering, and stacktrace truncating
- removed [orchestra](https://github.com/jeaye/orchestra) from default stacktrace filtering, since people might use it in their own code (ala @tonsky's [comment](https://github.com/lambdaisland/kaocha/issues/58#issuecomment-458555380))

Truncate irrelevant parts of stacktrace

---

README.md

I added kaocha-test-ns-hook plugin to 'Third party projects' section in README.md .
related discussions: https://github.com/lambdaisland/kaocha/issues/29

kaocha-test-ns-hook added to 'Third party projects' section in README.md

---

CHANGELOG.md
fixtures/d-tests/ddd/double_once_fixture_test.clj
src/kaocha/type/ns.clj
test/unit/kaocha/fixtures_test.clj

`:once` fixtures that call the provided `f` multiple times can swallow failures if the last call passes. Instead of swapping out the results of the `run-testables` call each time (which discards the existing failures), we should conj all calls together and return that as the completed result.
Related to #388

Once Fixtures calling f multiple times

---

CHANGELOG.md
src/kaocha/report.clj
test/unit/kaocha/report_test.clj

`kaocha.report/print-expression` requires `(seq? (second (:actual m)))` to be true to deep-diff output. This is true for `clojure.test`, which outputs `:actual (not (=...`, but not for `clojure-expectations`, whch outputs `:actual (not=...`.
This PR modifies `print-expression` to accept and parse both output formats for deep-diffing.
Resolves https://github.com/lambdaisland/kaocha/issues/435

deep-diff clojure-expectations' `:actual (not=` output format

---

test/unit/kaocha/plugin/notifier_test.clj

the notifier plugin never does anything on CI, causing this to fail

Skip notifier hook test on CI

---

CHANGELOG.md
doc/07_watch_mode.md
src/kaocha/watch.clj

Fixes https://github.com/lambdaisland/kaocha/issues/440
Thanks and kind regards

Fix beholder watch functionality. Improve docs.

---

README.md

Unfortunately, seems like linedict is no more, and the thing that replaced it doesn't seem to have pronunciation for 考察 (although it seems to be very happy to give five different pronunciations for the English translation "nose around"). 
Hanzii.net appears to be maintained, and has a nicer pronunciation (imo) than Forvo's Mandarin one. And Pleco is unfortunately still mobile only.

Update pronunciation link on README.md

---

CHANGELOG.md
src/kaocha/watch.clj

Hi again
And thanks again for a great project!
I've added a small change to transform *.ext to **.ext, as that is probably what the user wants.
*.ext will never match anything because beholder will produce fully qualified paths.
Thanks and kind regards
Ivar

Transform *.ext patterns to **.ext
